[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vzt = "HVHRr2JbMAT1zQ8N2vuWKctfV3ycvQYdDDzob1nqd6jD"

[provider]
cluster = "devnet"   # <-- PASTIKAN TULISANNYA DEVNET, BUKAN LOCALNET
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
